# Generated by Django 5.2.13 on 2026-05-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visitors', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='desktop_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='direct_traffic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='organic_traffic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_traffic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tablet_users',
            field=models.IntegerField(default=0),
        ),
    ]
