# Generated by Django 5.2.13 on 2026-05-28 15:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_bloganalytics_sitesettings_desktop_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='desktop_users',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='direct_traffic',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='mobile_users',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='organic_traffic',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='social_traffic',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='tablet_users',
        ),
        migrations.AddField(
            model_name='bloganalytics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloganalytics',
            name='desktop_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bloganalytics',
            name='direct_traffic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bloganalytics',
            name='mobile_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bloganalytics',
            name='organic_traffic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bloganalytics',
            name='social_traffic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bloganalytics',
            name='tablet_users',
            field=models.IntegerField(default=0),
        ),
    ]
