"""
Django settings for blog_main project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

from pathlib import Path


# =========================================================
# BASE DIRECTORY
# =========================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# =========================================================
# SECURITY
# =========================================================

SECRET_KEY = 'django-insecure-^9q_6@bj2r@&f^xla6b4xz0ezl%d!p^j5$by57#)t%@qf1d8&q'

DEBUG = True

ALLOWED_HOSTS = ["*"]


# =========================================================
# INSTALLED APPS
# =========================================================

INSTALLED_APPS = [

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # CUSTOM APPS

    'blogs',
    'assignments',
    'dashboards',
    'chatbot',

    # THIRD PARTY

    'crispy_forms',
    'crispy_bootstrap4',

    'ckeditor',
    'ckeditor_uploader',

]


# =========================================================
# MIDDLEWARE
# =========================================================

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]


# =========================================================
# ROOT URLS
# =========================================================

ROOT_URLCONF = 'blog_main.urls'


# =========================================================
# TEMPLATES
# =========================================================

TEMPLATES = [

    {

        'BACKEND':
        'django.template.backends.django.DjangoTemplates',

        'DIRS': [

            BASE_DIR / 'templates'

        ],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

                'blogs.context_processors.get_categories',

                'blogs.context_processors.get_social_links',

            ],

        },

    },

]


# =========================================================
# WSGI
# =========================================================

WSGI_APPLICATION = 'blog_main.wsgi.application'


# =========================================================
# DATABASE
# =========================================================

DATABASES = {

    'default': {

        'ENGINE':
        'django.db.backends.sqlite3',

        'NAME':
        BASE_DIR / 'db.sqlite3',

    }

}


# =========================================================
# PASSWORD VALIDATION
# =========================================================

AUTH_PASSWORD_VALIDATORS = [

    {

        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',

    },

    {

        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',

    },

    {

        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',

    },

    {

        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',

    },

]


# =========================================================
# INTERNATIONALIZATION
# =========================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Karachi'

USE_I18N = True

USE_TZ = True


# =========================================================
# STATIC FILES
# =========================================================

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [

    BASE_DIR / 'blog_main/static',

    BASE_DIR / 'static',

]


# =========================================================
# MEDIA FILES
# =========================================================

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'


# =========================================================
# CKEDITOR
# =========================================================

CKEDITOR_UPLOAD_PATH = 'uploads/'


# =========================================================
# CRISPY FORMS
# =========================================================

CRISPY_TEMPLATE_PACK = 'bootstrap4'


# =========================================================
# CSRF TRUSTED ORIGINS
# =========================================================

CSRF_TRUSTED_ORIGINS = [

    "http://127.0.0.1:8000",

    "http://localhost:8000",

]


# =========================================================
# AI API KEYS
# =========================================================

PEXELS_API_KEY = ''

GROQ_API_KEY = ''

GNEWS_API_KEY = ''

YOUTUBE_API_KEY = ''

WEB_SEARCH_API_KEY = ''


# =========================================================
# KD AI PREMIUM SETTINGS
# =========================================================

KD_AI_NAME = "KD AI"

KD_AI_THEME = "Premium Blue"

KD_AI_VOICE = "en-US"

KD_AI_ENABLE_VOICE = True

KD_AI_ENABLE_IMAGES = True

KD_AI_ENABLE_YOUTUBE = True

KD_AI_ENABLE_SEO = True

KD_AI_ENABLE_HUMANIZER = True

KD_AI_MAX_TOKENS = 7000

KD_YOUTUBE_VIDEO_COUNT = 3

KD_IMAGE_COUNT = 4


# =========================================================
# SESSION SETTINGS
# =========================================================

SESSION_COOKIE_AGE = 1209600

SESSION_SAVE_EVERY_REQUEST = True


# =========================================================
# LOGIN REDIRECTS
# =========================================================

LOGIN_REDIRECT_URL = "/"

LOGOUT_REDIRECT_URL = "/"


# =========================================================
# DEFAULT PRIMARY KEY
# =========================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'