# Generated by Django 5.2.13 on 2026-05-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIBlogDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(max_length=100)),
                ('meta_description', models.TextField()),
                ('tags', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('seo_score', models.IntegerField(default=0)),
                ('tone', models.CharField(blank=True, max_length=100)),
                ('grammar_score', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
