# Generated by Django 5.2.13 on 2026-05-10 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiblogdraft',
            name='ai_model',
            field=models.CharField(default='Gemini', max_length=100),
        ),
        migrations.AddField(
            model_name='aiblogdraft',
            name='ai_prompt',
            field=models.TextField(default='AI Blog Prompt'),
        ),
        migrations.AddField(
            model_name='aiblogdraft',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='ai_blogs/'),
        ),
        migrations.AddField(
            model_name='aiblogdraft',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiblogdraft',
            name='readability_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiblogdraft',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AIImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ai_blogs/')),
                ('alt_text', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chatbot.aiblogdraft')),
            ],
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('ai_response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
