# Generated by Django 5.2.13 on 2026-05-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_aichatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiblogdraft',
            name='admin_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aiblogdraft',
            name='conclusion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aiblogdraft',
            name='faq',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aiblogdraft',
            name='featured_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiblogdraft',
            name='publish_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiblogdraft',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aichatmessage',
            name='chat_title',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
