# Generated by Django 5.2.13 on 2026-05-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_aiblogdraft_admin_feedback_aiblogdraft_conclusion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiblogdraft',
            name='external_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aiblogdraft',
            name='inline_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aiblogdraft',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiblogdraft',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiblogdraft',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiblogdraft',
            name='youtube_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='aiblogdraft',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='aiblogdraft',
            name='tags',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='aiblogdraft',
            name='tone',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
