# Generated by Django 5.2.13 on 2026-05-22 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_aiblogdraft_external_links_aiblogdraft_inline_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_name', models.CharField(default='KD AI', max_length=100)),
                ('ai_voice', models.CharField(default='en-US', max_length=100)),
                ('ai_theme', models.CharField(default='Premium Blue', max_length=100)),
                ('enable_voice', models.BooleanField(default=True)),
                ('enable_youtube', models.BooleanField(default=True)),
                ('enable_images', models.BooleanField(default=True)),
                ('enable_seo', models.BooleanField(default=True)),
                ('enable_humanizer', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavedDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('prompt', models.TextField()),
                ('content', models.TextField()),
                ('category', models.CharField(default='General', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrendingBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='aiimage',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='aichatmessage',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='chathistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='chathistory',
            old_name='ai_response',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='chathistory',
            old_name='user_message',
            new_name='prompt',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='user',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='category',
            field=models.CharField(default='General', max_length=120),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='conclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='faq',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='featured_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='grammar_score',
            field=models.IntegerField(default=95),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='seo_score',
            field=models.IntegerField(default=95),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='tags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='title',
            field=models.CharField(default='KD AI Chat', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chathistory',
            name='tone',
            field=models.CharField(default='Professional', max_length=120),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='BlogAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('reading_time', models.CharField(default='5 min read', max_length=50)),
                ('engagement_score', models.IntegerField(default=90)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='chatbot.chathistory')),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.chathistory')),
            ],
        ),
        migrations.DeleteModel(
            name='AIBlogDraft',
        ),
        migrations.DeleteModel(
            name='AIImage',
        ),
        migrations.DeleteModel(
            name='AIChatMessage',
        ),
    ]
