# Generated by Django 5.2.13 on 2026-05-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_aisettings_saveddraft_trendingblog_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloganalytics',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='chathistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'AI Blog', 'verbose_name_plural': 'AI Blogs'},
        ),
        migrations.AlterModelOptions(
            name='saveddraft',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='trendingblog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='userfeedback',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='chathistory',
            name='image_gallery',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='reading_time',
            field=models.CharField(default='5 min read', max_length=50),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='shares',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=20),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='youtube_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='saveddraft',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
