# Generated by Django 5.2.13 on 2026-05-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
